// Single switch point onto the server's contract: everything UI-side imports
// table shapes from here, which re-exports shared/types.ts.
export type {
  Session,
  SessionSummary,
  SessionUsage,
  SessionDetail,
  StopReport,
  StoppedProcess,
  Phase,
  Event as EventRow,
  EventsPage,
  Envelope,
  GateResult,
  GateCheck,
  AgentSession,
  AgentStartPayload,
  AgentEndPayload,
  UsageBreakdown,
  ToolCallPayload,
  AgentPrompts,
  PromptsResponse,
  HealthResponse,
  SessionStatus,
  PhaseStatus,
  PhaseKind,
  EventType,
  AdwCatalog,
  AdwInfo,
  AdwOption,
  AdwDescription,
  Launch,
  LaunchPreview,
  LaunchRequest,
  LaunchState,
  Shell,
  IssueLink,
  IssueListing,
  IssueRerun,
  IssueRun,
  IssueVerdict,
  ReadyIssue,
} from '@shared/types'
